### ISSUE TITLE
no boot 

### ISSUE THREAD

**Issue by liyawolf** [yaoian/Razer_Blade_Stealth_2018_Hackintosh#3]
hi my friend, I came across your contribution for RBS 2018 because I have the same laptop with Big Sur installed previously. After downloaded the EFI folder to put in my USB flash drive EFI folder, I selected it to boot, it didn't do anything but booted in Windows directly. there was no selection of drive or picker. I wonder what could be wrong on my bois setup or anything I should make sure of.

Thank you for your time!

**Comment by yaoian** [comment]
Check `Misc`->`Boot`->`ShowPicker` to enable the boot selection

**Comment by liyawolf** [comment]
thank you for the prompt reply. It works great now for my Ventura. Thunderbolt works a USB C with DP, can drive USB C monitor, also USB C hub with HDMI can drive regular monitor. Fantastic job!  
My only issue right now is the screen flashes after load to desktop, I had to look screen then ESC to make the screen off then log on again to get screen works perfectly. now sure if you are aware of any possible reason.

**Comment by yaoian** [comment]
Yes, my monitor using HDMI connection would flash or even go black, under Windows as well, and it never worked out. Then I found out that the external monitor doesn't flash when I keep my headphones plugged in.

**Comment by liyawolf** [comment]
thanks for clarifying. it works all most perfectly now. I got RGB keyboard light worked by using: https://github.com/1kc/razer-macos
do you have Paypal? I'd like to send you some funds for coffee or something. Really hope that you can keep this laptop and project if you can. Again appreciate your effort!

**Comment by yaoian** [comment]
Thank you for your support. I've been using this laptop so I'll try to maintain this project.And looking forward to it running on macOS 14 and 15 in the future haha
